version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "teslabot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-merbocc95jbu"
s3_prefix = "teslabot"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["SentimentFunction=843154864268.dkr.ecr.us-east-1.amazonaws.com/teslabot6cc6bd50/sentimentfunction35d37012repo"]
